### ISSUE TITLE
Doesn't work with basic commands for Jesolver

### ISSUE THREAD

**Issue by carlo323** [weston/pyosolver#3]
I'm using Jesovler but it only works for root node, for every other node I'm encountering an error when I tried to run `print(solver.show_children("r:0:c"))` :

The debug log:
{'nodeID': 'ERROR: show_node incorrect path'}
('show_children', 'r:0:c')
ERROR: show_children incorrect path
END
```
Traceback (most recent call last):
    print(solver.show_children("r:0:c"))
    "nodeID": data[i+1],
IndexError: list index out of range

print(solver.show_children("r:0:c"))

**Comment by weston** [comment]
Thanks for reporting. Unfortunately I do not have a jesolver key, so I don't really have any way to test this.

**Comment by weston** [comment]
fixed show_children, so closing this for now
